language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=esp01_1m

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - pio lib install https://github.com/esp8266/Arduino/archive/master.zip
  - pio lib install "PubSubClient"
  - pio lib install "Adafruit BME280 Library"
  - pio lib install "Adafruit Unified Sensor" 
  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/ESPMQTTSense $PWD/Arduino\ Code/ESPMQTTSense/ESPMQTTSense.ino
  
notifications:
  email:
    on_success: change
    on_failure: change